backend:
  name: github
  repo: lukebennett88/hugo-starter
  branch: master

media_folder: "hugo/static/img" # Folder where user uploaded files should go
public_folder: "img"
collections:
  - name: "writing"
    label: "Writing"
    folder: "hugo/content/writing"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
