backend:
  name: github
  repo: zdizzle2009/block-commands
  branch: master

media_folder: "hugo/static/img" # Folder where user uploaded files should go
public_folder: "img"
collections:
  - name: "facts"
    label: "Fact"
    folder: "hugo/content/facts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "tutorials"
    label: "Tutorials"
    folder: "hugo/content/tutorials"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "videos"
    label: "Videos"
    folder: "hugo/content/vidoes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
